In [1]:
import numpy as np

In [2]:
a = np.array([2, 3, 5, 9])

In [3]:
type(a)

numpy.ndarray

In [4]:
a[0]

2

In [5]:
a.append(100)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
a = np.array([2, 3, 5, 9])

In [11]:
a

array([2, 3, 5, 9])

In [12]:
a.dtype

dtype('int64')

In [8]:
np.isnan(a)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [16]:
a = np.array([2, 3, 5, 9, np.nan]).astype("int32")
a

array([          2,           3,           5,           9, -2147483648],
      dtype=int32)

In [18]:
- 2 ** 31

-2147483648

In [24]:
a = np.array([2, 3, 5, 9, np.nan], dtype = "int32")
a.dtype

ValueError: cannot convert float NaN to integer

In [23]:
a

array([ 2.,  3.,  5.,  9., nan])

In [25]:
type(np.nan)

float

In [27]:
a = np.array([2, 3, 5, 9])


array([2, 3, 5, 9])

In [28]:
# Create 1m random numbers and 1. find standard deviation and 2. sort the values. Compare the timing required
# pure python and numpy

In [30]:
a = np.random.random(size = 1000000)
a.shape

(1000000,)

In [32]:
%%time
np.std(a)

CPU times: user 4.61 ms, sys: 1.13 ms, total: 5.73 ms
Wall time: 4.23 ms


0.28853333085058297

In [33]:
%%time
np.sort(a)

CPU times: user 90.8 ms, sys: 3.73 ms, total: 94.5 ms
Wall time: 94.6 ms


array([3.86585832e-07, 5.12607922e-07, 2.70102677e-06, ...,
       9.99998234e-01, 9.99998726e-01, 9.99999394e-01])

In [34]:
a = np.random.random(size = 10)
a

array([0.55720439, 0.39639341, 0.88395582, 0.50535145, 0.3172757 ,
       0.54394245, 0.72273144, 0.79595464, 0.01830642, 0.49560916])

In [37]:
np.argsort(a)

array([8, 4, 1, 9, 3, 5, 0, 6, 7, 2])

In [36]:
np.sort(a)

array([0.01830642, 0.3172757 , 0.39639341, 0.49560916, 0.50535145,
       0.54394245, 0.55720439, 0.72273144, 0.79595464, 0.88395582])

In [38]:
a

array([0.55720439, 0.39639341, 0.88395582, 0.50535145, 0.3172757 ,
       0.54394245, 0.72273144, 0.79595464, 0.01830642, 0.49560916])

In [40]:
a[0:3]

array([0.55720439, 0.39639341, 0.88395582])

In [41]:
a[[0, 4, 5]]

array([0.55720439, 0.3172757 , 0.54394245])

In [42]:
a[[0, 4, 4]]

array([0.55720439, 0.3172757 , 0.3172757 ])

In [43]:
a=np.random.random(size = (5, 3))
a

array([[0.08554877, 0.3266227 , 0.74031634],
       [0.66892709, 0.14544166, 0.32110764],
       [0.11755391, 0.69708419, 0.1524264 ],
       [0.30176295, 0.60446314, 0.10670254],
       [0.22943686, 0.71397664, 0.55664914]])

In [44]:
a[0]

array([0.08554877, 0.3266227 , 0.74031634])

In [45]:
a[0:2]

array([[0.08554877, 0.3266227 , 0.74031634],
       [0.66892709, 0.14544166, 0.32110764]])

In [46]:
a[[0, 0, 1]]

array([[0.08554877, 0.3266227 , 0.74031634],
       [0.08554877, 0.3266227 , 0.74031634],
       [0.66892709, 0.14544166, 0.32110764]])

In [47]:
a

array([[0.08554877, 0.3266227 , 0.74031634],
       [0.66892709, 0.14544166, 0.32110764],
       [0.11755391, 0.69708419, 0.1524264 ],
       [0.30176295, 0.60446314, 0.10670254],
       [0.22943686, 0.71397664, 0.55664914]])

In [48]:
a.T

array([[0.08554877, 0.66892709, 0.11755391, 0.30176295, 0.22943686],
       [0.3266227 , 0.14544166, 0.69708419, 0.60446314, 0.71397664],
       [0.74031634, 0.32110764, 0.1524264 , 0.10670254, 0.55664914]])

In [49]:
np.diag(a)

array([0.08554877, 0.14544166, 0.1524264 ])

In [50]:
a

array([[0.08554877, 0.3266227 , 0.74031634],
       [0.66892709, 0.14544166, 0.32110764],
       [0.11755391, 0.69708419, 0.1524264 ],
       [0.30176295, 0.60446314, 0.10670254],
       [0.22943686, 0.71397664, 0.55664914]])

In [51]:
a + 10

array([[10.08554877, 10.3266227 , 10.74031634],
       [10.66892709, 10.14544166, 10.32110764],
       [10.11755391, 10.69708419, 10.1524264 ],
       [10.30176295, 10.60446314, 10.10670254],
       [10.22943686, 10.71397664, 10.55664914]])

In [52]:
a * 2

array([[0.17109754, 0.65324539, 1.48063268],
       [1.33785418, 0.29088333, 0.64221528],
       [0.23510782, 1.39416838, 0.3048528 ],
       [0.60352591, 1.20892627, 0.21340508],
       [0.45887371, 1.42795329, 1.11329828]])

In [53]:
a

array([[0.08554877, 0.3266227 , 0.74031634],
       [0.66892709, 0.14544166, 0.32110764],
       [0.11755391, 0.69708419, 0.1524264 ],
       [0.30176295, 0.60446314, 0.10670254],
       [0.22943686, 0.71397664, 0.55664914]])

In [54]:
a.mean()

0.3845346645138407

In [56]:
a.flatten().mean()

0.3845346645138407

In [57]:
a.mean(axis = 1)

array([0.3841626 , 0.37849213, 0.32235483, 0.33764288, 0.50002088])

In [58]:
np.mean([0.08554877, 0.3266227 , 0.74031634])

0.38416260333333335

In [59]:
a.mean(axis = 0)

array([0.28064592, 0.49751767, 0.37544041])

In [60]:
a[:, 0]

array([0.08554877, 0.66892709, 0.11755391, 0.30176295, 0.22943686])

In [61]:
a[:, 0].mean()

0.28064591569827474

In [62]:
a=np.random.random(size = (5, 3))
a

array([[0.06244924, 0.51242378, 0.28254982],
       [0.88423622, 0.69892267, 0.88879312],
       [0.36947517, 0.22863533, 0.42942332],
       [0.22666   , 0.25383173, 0.92265426],
       [0.80066264, 0.57305616, 0.99321339]])

In [63]:
b=np.random.random(size = (3, 10))

In [65]:
a.dot(b).shape

(5, 10)

In [66]:
import pandas as pd

In [68]:
# dataframe (2D) - each column is a series .. and they can be diff , series (1D) - single type

In [69]:
df = pd.read_csv("https://raw.githubusercontent.com/abulbasar/data/master/diamonds.csv")

In [70]:
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [71]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df.shape

(53940, 10)

In [73]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [74]:
df.dtypes

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [75]:
df["carat"]

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ... 
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [76]:
df.carat

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ... 
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [77]:
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [78]:
df.tail()

,carat,cut,color,clarity,depth,table,price,x,y,z
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64


In [91]:
np.random.seed(1)
np.random.random(3)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [84]:
df.sample(10, random_state=12)

,carat,cut,color,clarity,depth,table,price,x,y,z
45936,0.51,Very Good,F,VS1,63.3,59.0,1722,5.09,5.12,3.23
23023,0.35,Ideal,E,SI2,61.4,56.0,630,4.55,4.51,2.78
34325,0.39,Premium,E,SI1,59.1,59.0,860,4.81,4.76,2.83
38578,0.40,Ideal,G,VS2,62.9,56.0,1035,4.72,4.69,2.96
15979,1.20,Premium,E,SI2,62.6,56.0,6397,6.84,6.77,4.26
31000,0.35,Ideal,E,VS1,62.3,57.0,747,4.51,4.55,2.82
7330,0.91,Very Good,G,VS1,63.2,58.0,4209,6.15,6.07,3.86
3448,0.91,Very Good,G,SI2,61.8,59.0,3388,6.17,6.23,3.83
51867,0.78,Ideal,J,VS1,61.4,57.0,2426,5.90,5.93,3.63
36552,0.40,Ideal,E,SI1,62.2,55.0,945,4.75,4.71,2.94


In [94]:
df.iloc[10:20]

,carat,cut,color,clarity,depth,table,price,x,y,z
10,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
12,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
15,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68
16,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
17,0.30,Good,J,SI1,63.4,54.0,351,4.23,4.29,2.70
18,0.30,Good,J,SI1,63.8,56.0,351,4.23,4.26,2.71
19,0.30,Very Good,J,SI1,62.7,59.0,351,4.21,4.27,2.66


In [95]:
df.index

RangeIndex(start=0, stop=53940, step=1)

In [96]:
df.iloc[[0, 3, 8]]

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49


In [97]:
df.iloc[:, :3]

,carat,cut,color
0,0.23,Ideal,E
1,0.21,Premium,E
2,0.23,Good,E
3,0.29,Premium,I
4,0.31,Good,J
...,...,...,...
53935,0.72,Ideal,D
53936,0.72,Good,D
53937,0.70,Very Good,D
53938,0.86,Premium,H


In [99]:
df.iloc[:, [0, 3, 6]]

,carat,clarity,price
0,0.23,SI2,326
1,0.21,SI1,326
2,0.23,VS1,327
3,0.29,VS2,334
4,0.31,SI2,335
...,...,...,...
53935,0.72,SI1,2757
53936,0.72,SI1,2757
53937,0.70,SI1,2757
53938,0.86,SI2,2757


In [100]:
df[["carat", "clarity", "price"]]

,carat,clarity,price
0,0.23,SI2,326
1,0.21,SI1,326
2,0.23,VS1,327
3,0.29,VS2,334
4,0.31,SI2,335
...,...,...,...
53935,0.72,SI1,2757
53936,0.72,SI1,2757
53937,0.70,SI1,2757
53938,0.86,SI2,2757


In [101]:
# how to navigate through by rows, columns, or randomly  - slice and dicing

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74


In [103]:
# filter, sort, aggregate, pivot, join, mutate

In [105]:
df[df.cut == "Ideal"]

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
16,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
39,0.33,Ideal,I,SI2,61.8,55.0,403,4.49,4.51,2.78
...,...,...,...,...,...,...,...,...,...,...
53925,0.79,Ideal,I,SI1,61.6,56.0,2756,5.95,5.97,3.67
53926,0.71,Ideal,E,SI1,61.9,56.0,2756,5.71,5.73,3.54
53929,0.71,Ideal,G,VS1,61.4,56.0,2756,5.76,5.73,3.53
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50


In [106]:
df.shape

(53940, 10)

In [112]:
%%time
df[(df.cut == "Ideal") & (df.color == "J")]

CPU times: user 8.37 ms, sys: 1.85 ms, total: 10.2 ms
Wall time: 8.91 ms


,carat,cut,color,clarity,depth,table,price,x,y,z
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
41,0.33,Ideal,J,SI1,61.1,56.0,403,4.49,4.55,2.76
460,0.90,Ideal,J,VS2,62.8,55.0,2817,6.20,6.16,3.88
681,0.75,Ideal,J,SI1,61.5,56.0,2850,5.83,5.87,3.60
...,...,...,...,...,...,...,...,...,...,...
53598,0.71,Ideal,J,SI1,60.6,57.0,2700,5.78,5.83,3.52
53666,0.81,Ideal,J,VS2,62.1,56.0,2708,5.92,5.97,3.69
53670,0.84,Ideal,J,VS2,61.1,57.0,2709,6.09,6.12,3.73
53848,0.82,Ideal,J,VS2,61.6,56.0,2741,6.00,6.04,3.71


In [108]:
df.cut == "Ideal"

0         True
1        False
2        False
3        False
4        False
         ...  
53935     True
53936    False
53937    False
53938    False
53939     True
Name: cut, Length: 53940, dtype: bool

In [111]:
%%time 
df.query("cut == 'Ideal' and color == 'J'")

CPU times: user 8.86 ms, sys: 2.34 ms, total: 11.2 ms
Wall time: 9.49 ms


,carat,cut,color,clarity,depth,table,price,x,y,z
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
41,0.33,Ideal,J,SI1,61.1,56.0,403,4.49,4.55,2.76
460,0.90,Ideal,J,VS2,62.8,55.0,2817,6.20,6.16,3.88
681,0.75,Ideal,J,SI1,61.5,56.0,2850,5.83,5.87,3.60
...,...,...,...,...,...,...,...,...,...,...
53598,0.71,Ideal,J,SI1,60.6,57.0,2700,5.78,5.83,3.52
53666,0.81,Ideal,J,VS2,62.1,56.0,2708,5.92,5.97,3.69
53670,0.84,Ideal,J,VS2,61.1,57.0,2709,6.09,6.12,3.73
53848,0.82,Ideal,J,VS2,61.6,56.0,2741,6.00,6.04,3.71


In [113]:
%%time 
df.query("cut == 'Ideal'").query("color == 'J'")

CPU times: user 9.86 ms, sys: 2.28 ms, total: 12.1 ms
Wall time: 10.2 ms


,carat,cut,color,clarity,depth,table,price,x,y,z
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
41,0.33,Ideal,J,SI1,61.1,56.0,403,4.49,4.55,2.76
460,0.90,Ideal,J,VS2,62.8,55.0,2817,6.20,6.16,3.88
681,0.75,Ideal,J,SI1,61.5,56.0,2850,5.83,5.87,3.60
...,...,...,...,...,...,...,...,...,...,...
53598,0.71,Ideal,J,SI1,60.6,57.0,2700,5.78,5.83,3.52
53666,0.81,Ideal,J,VS2,62.1,56.0,2708,5.92,5.97,3.69
53670,0.84,Ideal,J,VS2,61.1,57.0,2709,6.09,6.12,3.73
53848,0.82,Ideal,J,VS2,61.6,56.0,2741,6.00,6.04,3.71


In [115]:
%%time 
df.query("cut == 'Ideal' and color == 'J' and price > 2000")

CPU times: user 8.82 ms, sys: 2.02 ms, total: 10.8 ms
Wall time: 8.88 ms


,carat,cut,color,clarity,depth,table,price,x,y,z
460,0.90,Ideal,J,VS2,62.8,55.0,2817,6.20,6.16,3.88
681,0.75,Ideal,J,SI1,61.5,56.0,2850,5.83,5.87,3.60
918,1.02,Ideal,J,SI2,60.3,54.0,2879,6.53,6.50,3.93
1763,1.14,Ideal,J,SI1,60.2,57.0,3045,6.81,6.71,4.07
1778,0.90,Ideal,J,VS1,62.6,55.0,3048,6.13,6.11,3.83
...,...,...,...,...,...,...,...,...,...,...
53598,0.71,Ideal,J,SI1,60.6,57.0,2700,5.78,5.83,3.52
53666,0.81,Ideal,J,VS2,62.1,56.0,2708,5.92,5.97,3.69
53670,0.84,Ideal,J,VS2,61.1,57.0,2709,6.09,6.12,3.73
53848,0.82,Ideal,J,VS2,61.6,56.0,2741,6.00,6.04,3.71


In [119]:
df2 = df.sort_values("carat", ascending = False).copy()

In [120]:
df2

,carat,cut,color,clarity,depth,table,price,x,y,z
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
...,...,...,...,...,...,...,...,...,...,...
31592,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24
31591,0.20,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26
31601,0.20,Premium,D,VS2,61.7,60.0,367,3.77,3.72,2.31
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27


In [122]:
df.sort_values(["carat", "price"])

,carat,cut,color,clarity,depth,table,price,x,y,z
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
31591,0.20,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26
31592,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24
31593,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32
31594,0.20,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28
...,...,...,...,...,...,...,...,...,...,...
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72


In [124]:
df.sort_values(["carat", "price"], ascending = False)

,carat,cut,color,clarity,depth,table,price,x,y,z
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
...,...,...,...,...,...,...,...,...,...,...
31598,0.20,Very Good,E,VS2,63.4,59.0,367,3.74,3.71,2.36
31599,0.20,Ideal,E,VS2,62.2,57.0,367,3.76,3.73,2.33
31600,0.20,Premium,D,VS2,62.3,60.0,367,3.73,3.68,2.31
31601,0.20,Premium,D,VS2,61.7,60.0,367,3.77,3.72,2.31


In [125]:
df.sort_values(["carat", "price"], ascending = [True, False])

,carat,cut,color,clarity,depth,table,price,x,y,z
31591,0.20,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26
31592,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24
31593,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32
31594,0.20,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28
31595,0.20,Ideal,E,VS2,59.7,55.0,367,3.86,3.84,2.30
...,...,...,...,...,...,...,...,...,...,...
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72


In [129]:
df.sort_values(["carat", "price"], ascending = [True, False]).query("carat == 0.2")

,carat,cut,color,clarity,depth,table,price,x,y,z
31591,0.2,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26
31592,0.2,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24
31593,0.2,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32
31594,0.2,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28
31595,0.2,Ideal,E,VS2,59.7,55.0,367,3.86,3.84,2.30
31596,0.2,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33
31597,0.2,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33
31598,0.2,Very Good,E,VS2,63.4,59.0,367,3.74,3.71,2.36
31599,0.2,Ideal,E,VS2,62.2,57.0,367,3.76,3.73,2.33
31600,0.2,Premium,D,VS2,62.3,60.0,367,3.73,3.68,2.31


In [131]:
df.cut.value_counts()

Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: cut, dtype: int64

In [133]:
df.groupby("cut").price.mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [134]:
df.groupby("cut").price.count()

cut
Fair          1610
Good          4906
Ideal        21551
Premium      13791
Very Good    12082
Name: price, dtype: int64

In [135]:
df.groupby("cut").price.agg(["mean", "count"])

,mean,count
cut,,
Fair,4358.757764,1610
Good,3928.864452,4906
Ideal,3457.541970,21551
Premium,4584.257704,13791
Very Good,3981.759891,12082


In [136]:
df.groupby("cut").price.agg(["mean", "count", "std", "min", "max"])

,mean,count,std,min,max
cut,,,,,
Fair,4358.757764,1610,3560.386612,337,18574
Good,3928.864452,4906,3681.589584,327,18788
Ideal,3457.541970,21551,3808.401172,326,18806
Premium,4584.257704,13791,4349.204961,326,18823
Very Good,3981.759891,12082,3935.862161,336,18818


In [161]:
df.groupby("cut")[["carat", "price"]].mean()

,carat,price
cut,,
Fair,1.046137,4358.757764
Good,0.849185,3928.864452
Ideal,0.702837,3457.541970
Premium,0.891955,4584.257704
Very Good,0.806381,3981.759891


In [162]:
df.groupby("cut")[["carat", "price"]].agg(["min", "max"])

carat       price       
            min   max   min    max
cut                               
Fair       0.22  5.01   337  18574
Good       0.23  3.01   327  18788
Ideal      0.20  3.50   326  18806
Premium    0.20  4.01   326  18823
Very Good  0.20  4.00   336  18818

In [163]:
df.groupby("cut").agg({"carat": ["min", "max"], "price":["mean", "std"]})

carat              price             
            min   max         mean          std
cut                                            
Fair       0.22  5.01  4358.757764  3560.386612
Good       0.23  3.01  3928.864452  3681.589584
Ideal      0.20  3.50  3457.541970  3808.401172
Premium    0.20  4.01  4584.257704  4349.204961
Very Good  0.20  4.00  3981.759891  3935.862161

In [165]:
a = df.groupby(["cut", "color"]).agg({"carat": ["min", "max"], "price":["mean", "std"]})
a

carat              price             
                  min   max         mean          std
cut       color                                      
Fair      D      0.25  3.40  4291.061350  3286.114238
          E      0.22  2.04  3682.312500  2976.651645
          F      0.25  2.58  3827.003205  3223.302685
          G      0.23  2.60  4239.254777  3609.644379
          H      0.33  4.13  5135.683168  3886.481847
          I      0.41  3.02  4685.445714  3730.271132
          J      0.30  5.01  4975.655462  4050.458933
Good      D      0.23  2.04  3405.382175  3175.148710
          E      0.23  3.00  3423.644159  3330.702061
          F      0.23  2.67  3495.750275  3202.411187
          G      0.23  2.80  4123.482204  3702.504718
          H      0.25  3.01  4276.254986  4020.660488
          I      0.30  3.01  5078.532567  4631.702141
          J      0.28  3.00  4574.172638  3707.790845
Ideal     D      0.20  2.75  2629.094566  3001.069919
          E      0.20  2.28  2597.550090  2956.007149
          F      0.23  2.45  3374.939362  3766.635328
          G      0.23  2.54  3720.706388  4006.262468
          H      0.23  3.50  3889.334831  4013.375228
          I      0.23  3.22  4451.970377  4505.150405
          J      0.23  3.01  4918.186384  4476.206836
Premium   D      0.20  2.57  3631.292576  3711.634010
          E      0.20  3.05  3538.914420  3794.987184
          F      0.20  3.01  4324.890176  4012.022756
          G      0.23  3.01  4500.742134  4356.571034
          H      0.23  3.24  5216.706780  4466.189717
          I      0.23  4.01  5946.180672  5053.746146
          J      0.30  4.01  6294.591584  4788.936691
Very Good D      0.23  2.58  3470.467284  3523.753268
          E      0.20  2.51  3214.652083  3408.023634
          F      0.23  2.48  3778.820240  3786.124033
          G      0.23  2.52  3872.753806  3861.375464
          H      0.23  3.00  4535.390351  4185.798202
          I      0.24  4.00  5255.879568  4687.104775
          J      0.24  2.74  5103.513274  4135.652742

In [172]:
a.loc["Fair", "E"]["price"]["mean"]

3682.3125

In [277]:
a.columns= a.columns.to_flat_index()
a.reset_index()

,cut,color,"(carat, min)","(carat, max)","(price, mean)","(price, std)"
0,Fair,D,0.25,3.40,4291.061350,3286.114238
1,Fair,E,0.22,2.04,3682.312500,2976.651645
2,Fair,F,0.25,2.58,3827.003205,3223.302685
3,Fair,G,0.23,2.60,4239.254777,3609.644379
4,Fair,H,0.33,4.13,5135.683168,3886.481847
5,Fair,I,0.41,3.02,4685.445714,3730.271132
6,Fair,J,0.30,5.01,4975.655462,4050.458933
7,Good,D,0.23,2.04,3405.382175,3175.148710
8,Good,E,0.23,3.00,3423.644159,3330.702061
9,Good,F,0.23,2.67,3495.750275,3202.411187


In [176]:
a.reset_index()#.query("cut == 'Fair' and color == 'E'")

cut color carat              price             
                      min   max         mean          std
0        Fair     D  0.25  3.40  4291.061350  3286.114238
1        Fair     E  0.22  2.04  3682.312500  2976.651645
2        Fair     F  0.25  2.58  3827.003205  3223.302685
3        Fair     G  0.23  2.60  4239.254777  3609.644379
4        Fair     H  0.33  4.13  5135.683168  3886.481847
5        Fair     I  0.41  3.02  4685.445714  3730.271132
6        Fair     J  0.30  5.01  4975.655462  4050.458933
7        Good     D  0.23  2.04  3405.382175  3175.148710
8        Good     E  0.23  3.00  3423.644159  3330.702061
9        Good     F  0.23  2.67  3495.750275  3202.411187
10       Good     G  0.23  2.80  4123.482204  3702.504718
11       Good     H  0.25  3.01  4276.254986  4020.660488
12       Good     I  0.30  3.01  5078.532567  4631.702141
13       Good     J  0.28  3.00  4574.172638  3707.790845
14      Ideal     D  0.20  2.75  2629.094566  3001.069919
15      Ideal     E  0.20  2.28  2597.550090  2956.007149
16      Ideal     F  0.23  2.45  3374.939362  3766.635328
17      Ideal     G  0.23  2.54  3720.706388  4006.262468
18      Ideal     H  0.23  3.50  3889.334831  4013.375228
19      Ideal     I  0.23  3.22  4451.970377  4505.150405
20      Ideal     J  0.23  3.01  4918.186384  4476.206836
21    Premium     D  0.20  2.57  3631.292576  3711.634010
22    Premium     E  0.20  3.05  3538.914420  3794.987184
23    Premium     F  0.20  3.01  4324.890176  4012.022756
24    Premium     G  0.23  3.01  4500.742134  4356.571034
25    Premium     H  0.23  3.24  5216.706780  4466.189717
26    Premium     I  0.23  4.01  5946.180672  5053.746146
27    Premium     J  0.30  4.01  6294.591584  4788.936691
28  Very Good     D  0.23  2.58  3470.467284  3523.753268
29  Very Good     E  0.20  2.51  3214.652083  3408.023634
30  Very Good     F  0.23  2.48  3778.820240  3786.124033
31  Very Good     G  0.23  2.52  3872.753806  3861.375464
32  Very Good     H  0.23  3.00  4535.390351  4185.798202
33  Very Good     I  0.24  4.00  5255.879568  4687.104775
34  Very Good     J  0.24  2.74  5103.513274  4135.652742

In [138]:
df.dtypes

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object 
 2   color    53940 non-null  object 
 3   clarity  53940 non-null  object 
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64  
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB


In [157]:
df2 = pd.read_csv("/Users/abasar/data/startups.csv")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        48 non-null     object 
 1   Administration   50 non-null     float64
 2   Marketing Spend  47 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(3), object(2)
memory usage: 2.1+ KB


In [158]:
def to_float(s):
    try:
        return float(s)
    except:
        return np.nan
    
df2["R&D Spend"] = df2["R&D Spend"].apply(to_float)

In [159]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        47 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  47 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [160]:
df2

,R&D Spend,Administration,Marketing Spend,State,Profit
0,NaN,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94
5,131876.90,99814.71,362861.36,New York,156991.12
6,134615.46,147198.87,127716.82,California,156122.51
7,130298.13,145530.06,323876.68,Florida,155752.60
8,120542.52,148718.95,311613.29,New York,152211.77
9,123334.88,108679.17,304981.62,California,149759.96


In [182]:
df.pivot_table("price", "cut", "color", aggfunc="mean")

color,D,E,F,G,H,I,J
cut,,,,,,,
Fair,4291.061350,3682.312500,3827.003205,4239.254777,5135.683168,4685.445714,4975.655462
Good,3405.382175,3423.644159,3495.750275,4123.482204,4276.254986,5078.532567,4574.172638
Ideal,2629.094566,2597.550090,3374.939362,3720.706388,3889.334831,4451.970377,4918.186384
Premium,3631.292576,3538.914420,4324.890176,4500.742134,5216.706780,5946.180672,6294.591584
Very Good,3470.467284,3214.652083,3778.820240,3872.753806,4535.390351,5255.879568,5103.513274


In [187]:
df.pivot_table("price", "cut", "color", aggfunc="mean")

color,D,E,F,G,H,I,J
cut,,,,,,,
Fair,4291.061350,3682.312500,3827.003205,4239.254777,5135.683168,4685.445714,4975.655462
Good,3405.382175,3423.644159,3495.750275,4123.482204,4276.254986,5078.532567,4574.172638
Ideal,2629.094566,2597.550090,3374.939362,3720.706388,3889.334831,4451.970377,4918.186384
Premium,3631.292576,3538.914420,4324.890176,4500.742134,5216.706780,5946.180672,6294.591584
Very Good,3470.467284,3214.652083,3778.820240,3872.753806,4535.390351,5255.879568,5103.513274


In [188]:
df.query("cut == 'Ideal' and color == 'I'").price.mean()

4451.970377448638

In [189]:
movies = pd.read_csv("https://raw.githubusercontent.com/abulbasar/data/master/movielens/movies.csv")
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9120,162672,Mohenjo Daro (2016),Adventure|Drama|Romance
9121,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary
9123,164977,The Gay Desperado (1936),Comedy


In [190]:
ratings = pd.read_csv("https://raw.githubusercontent.com/abulbasar/data/master/movielens/ratings.csv")
ratings

,userId,movieId,rating,timestamp
0,1,31,2.5,1260759144
1,1,1029,3.0,1260759179
2,1,1061,3.0,1260759182
3,1,1129,2.0,1260759185
4,1,1172,4.0,1260759205
...,...,...,...,...
99999,671,6268,2.5,1065579370
100000,671,6269,4.0,1065149201
100001,671,6365,4.0,1070940363
100002,671,6385,2.5,1070979663


In [194]:
ratings.groupby("movieId").rating.agg(["mean", "count"]).reset_index().merge(movies, on = "movieId")

,movieId,mean,count,title,genres
0,1,3.872470,247,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,3.401869,107,Jumanji (1995),Adventure|Children|Fantasy
2,3,3.161017,59,Grumpier Old Men (1995),Comedy|Romance
3,4,2.384615,13,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,3.267857,56,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...
9061,161944,5.000000,1,The Last Brickmaker in America (2001),Drama
9062,162376,4.500000,1,Stranger Things,Drama
9063,162542,5.000000,1,Rustom (2016),Romance|Thriller
9064,162672,3.000000,1,Mohenjo Daro (2016),Adventure|Drama|Romance


In [195]:
ratings.groupby("movieId").rating.agg(["mean", "count"]).reset_index().merge(movies, left_on = "movieId", right_on = "movieId")

,movieId,mean,count,title,genres
0,1,3.872470,247,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,3.401869,107,Jumanji (1995),Adventure|Children|Fantasy
2,3,3.161017,59,Grumpier Old Men (1995),Comedy|Romance
3,4,2.384615,13,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,3.267857,56,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...
9061,161944,5.000000,1,The Last Brickmaker in America (2001),Drama
9062,162376,4.500000,1,Stranger Things,Drama
9063,162542,5.000000,1,Rustom (2016),Romance|Thriller
9064,162672,3.000000,1,Mohenjo Daro (2016),Adventure|Drama|Romance


In [197]:
ratings.groupby("movieId").rating.agg(["mean", "count"]).merge(movies, left_index = True, right_on = "movieId")

,mean,count,movieId,title,genres
0,3.872470,247,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,3.401869,107,2,Jumanji (1995),Adventure|Children|Fantasy
2,3.161017,59,3,Grumpier Old Men (1995),Comedy|Romance
3,2.384615,13,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,3.267857,56,5,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...
9117,5.000000,1,161944,The Last Brickmaker in America (2001),Drama
9118,4.500000,1,162376,Stranger Things,Drama
9119,5.000000,1,162542,Rustom (2016),Romance|Thriller
9120,3.000000,1,162672,Mohenjo Daro (2016),Adventure|Drama|Romance


In [198]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9120,162672,Mohenjo Daro (2016),Adventure|Drama|Romance
9121,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary
9123,164977,The Gay Desperado (1936),Comedy


In [199]:
import re

In [216]:

p = re.compile(r"\((\d{4})\)")

def extract_year(s):
    m = p.search(s)
    if m:
        return m.group(1)

extract_year("The Gay Desperado (1936)")

'1936'

In [217]:
movies["year"] = movies.title.apply(extract_year)

In [218]:
movies

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
9120,162672,Mohenjo Daro (2016),Adventure|Drama|Romance,2016
9121,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi,2016
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,2016
9123,164977,The Gay Desperado (1936),Comedy,1936


In [219]:
count_by_movieId = ratings.movieId.value_counts()

In [222]:
movies["rating_count"] = movies.movieId.apply(lambda v: count_by_movieId.get(v))
movies

,movieId,title,genres,year,rating_count
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,247.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,107.0
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,59.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,13.0
4,5,Father of the Bride Part II (1995),Comedy,1995,56.0
...,...,...,...,...,...
9120,162672,Mohenjo Daro (2016),Adventure|Drama|Romance,2016,1.0
9121,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi,2016,NaN
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,2016,1.0
9123,164977,The Gay Desperado (1936),Comedy,1936,NaN


In [225]:
ratings[ratings.movieId == 4].shape

(13, 4)

In [236]:
def my_mean(a):
    return np.mean(a)

def most_common(a):
    m = stats.mode(a)
    return m.mode[0]

ratings.groupby("movieId").rating.agg(["mean", "count", my_mean, most_common])

,mean,count,my_mean,most_common
movieId,,,,
1,3.872470,247,3.872470,4.0
2,3.401869,107,3.401869,3.0
3,3.161017,59,3.161017,3.0
4,2.384615,13,2.384615,3.0
5,3.267857,56,3.267857,3.0
...,...,...,...,...
161944,5.000000,1,5.000000,5.0
162376,4.500000,1,4.500000,4.5
162542,5.000000,1,5.000000,5.0


In [229]:
from scipy import stats

In [233]:
m = stats.mode([2, 3, 4,5,5, 5, 4, 4])
m

ModeResult(mode=array([4]), count=array([3]))

In [235]:
m.mode[0]

4

In [237]:
def my_mean(a):
    return np.mean(a)

def most_common(a):
    m = stats.mode(a)
    return m.mode[0]

def my_count(a):
    return len(a)

ratings.groupby("movieId").rating.agg(["mean", "count", my_mean, most_common, my_count])

,mean,count,my_mean,most_common,my_count
movieId,,,,,
1,3.872470,247,3.872470,4.0,247.0
2,3.401869,107,3.401869,3.0,107.0
3,3.161017,59,3.161017,3.0,59.0
4,2.384615,13,2.384615,3.0,13.0
5,3.267857,56,3.267857,3.0,56.0
...,...,...,...,...,...
161944,5.000000,1,5.000000,5.0,1.0
162376,4.500000,1,4.500000,4.5,1.0
162542,5.000000,1,5.000000,5.0,1.0


In [278]:
titanic = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
